name: Docker Build

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Debug secrets
        run: |
          echo "Username length: ${#DOCKER_USERNAME}"
          echo "Password length: ${#DOCKER_PASSWORD}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            BPCS_VER=${{ inputs.tag }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/baidupcs-go:${{ inputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/baidupcs-go:latest
